FROM python:3.10-alpine
ADD server.py .
ADD requirements.txt .
RUN mkdir ./templates
COPY ./templates/index.html ./templates/index.html

RUN pip install -r requirements.txt
CMD ["python", "./server.py"]